#!/bin/sh

FLAGS=$1

if [[ ! -z "$FLAGS" ]]; then
  FLAGS=.${FLAGS}
fi

rm -rf build
mkdir build
cd build

#IDL_ROOT_DIR=/opt/share/idl8.6/idl86
IDL_ROOT_DIR=/opt/share/idl8.7.3/idl87

cmake \
  -DCMAKE_INSTALL_PREFIX:PATH=~/software/ucomp-pipeline${FLAGS} \
  -DIDL_ROOT_DIR:PATH=${IDL_ROOT_DIR} \
  ..
