#!/bin/sh

FLAGS=$1

if [[ ! -z "$FLAGS" ]]; then
  FLAGS=.${FLAGS}
fi

rm -rf build
mkdir build
cd build

IDL_ROOT_DIR=/Applications/harris/idl

cmake \
  -DCMAKE_INSTALL_PREFIX:PATH=~/software/ucomp-pipeline${FLAGS} \
  -DIDL_ROOT_DIR:PATH=${IDL_ROOT_DIR} \
  ..
